### ISSUE TITLE
Port beeing used

### ISSUE THREAD

**Issue by MagnusTim** [mmajcica/DeploySsis#1]
Hi,

Thanks for a nice tool. 

We get a timeoutproblem connecting to the database:
Failed to connect to server xxx. ---> System.Data.SqlClient.SqlException: Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.

My idea is that it could be a firewall issue. Are you using remot powershell (5985) or a SQL port when doing the deploy?

Regards Magnus

**Comment by mmajcica** [comment]
Hi Magnus,

you are welcome.

I'm using this task in a TFS Release o several projects with success. 

All of the communication logic is laid in the following two libraries, Microsoft.SqlServer.Smo and Microsoft.SqlServer.Management.IntegrationServices. If I'm not wrong, they both rely on SQL port which should be by default set to 1433.

Can you check and let me know if enabling the communication in between your agent and your SQL server on port 1433 does the trick?

Regards
Mario

**Comment by MagnusTim** [comment]
It worked when we opened 1433, thanks!

/Magnus

Från: Mario Majcica <notifications@github.com>
Skickat: den 21 mars 2018 14:25
Till: mmajcica/DeploySsis <DeploySsis@noreply.github.com>
Kopia: Magnus <magnus@timner.se>; Author <author@noreply.github.com>
Ämne: Re: [mmajcica/DeploySsis] Port beeing used (#1)


Hi Magnus,

you are welcome.

I'm using this task in a TFS Release o several projects with success.

All of the communication logic is laid in the following two libraries, Microsoft.SqlServer.Smo and Microsoft.SqlServer.Management.IntegrationServices. If I'm not wrong, they both rely on SQL port which should be by default set to 1433.

Can you check and let me know if enabling the communication in between your agent and your SQL server on port 1433 does the trick?

Regards
Mario
