### ISSUE TITLE
how to add custom project name

### ISSUE THREAD

**Issue by BKB503** [mmajcica/DeploySsis#12]
how to provide custom project name when deploying ?

**Comment by mmajcica** [comment]
Can you be a bit more specific as I do not understand what are you trying to achieve?

**Comment by BKB503** [comment]
@mmajcica  when deploying  SSIS Catalog --> CreateFolder or existing folder --> Projects if using same ISPAC but different project name  (custom project name) able to deploy from release pipeline

you can see in this market place example
I have been looking into this market place https://marketplace.visualstudio.com/items?itemName=TG.VSTS-SSIS
https://tg.gallerycdn.vsassets.io/extensions/tg/vsts-ssis/1.0.1151/1526304857712/images/deploy.png

**Comment by mmajcica** [comment]
I'm sorry but I still do not get it. Are you trying to deploy the same package in two folders? Why then not settings the SSIS folder name in two instances of the task and proceed?

**Comment by BKB503** [comment]
when building ispac with abc.edf.ispac I want to deploy with xyz_123.ispac as a custom name option in the release pipeline, if not you can close this issue. 

In Visual studio when we build to ispac if project name is set to abc.edf it will convert to abc_edf, so i thought to check is there any of having custom name so that i can reference abc_edf ispac and when deploying to sql server it can be abc.edf ispac or any name

**Comment by mmajcica** [comment]
No, unfortunately, there is no such functionality. Items can't be renamed with this task.
