### ISSUE TITLE
Cannot use this task in Azure DevOps

### ISSUE THREAD

**Issue by linxtong** [mmajcica/DeploySsis#13]
Hi Mario, 
Thanks very much for your sharing,
Today I try to build a CI CD pipeline for my SSIS project, I found your great work in market place which is exactly what I want to have.
But after I installed it in AzureDevops Site, I cannot use it in my pipeline, it is still in the Marketplace tab with the grey Installed button.

Could you please have a look?

thanks again.

linxtong

**Comment by mmajcica** [comment]
Hi,

I just checked it and it looks good:

![image](https://user-images.githubusercontent.com/3026551/54417804-7979a500-4703-11e9-8169-3d02d9b86f9e.png)

It is still working exactly as described here
http://blog.majcica.com/2018/04/25/deploy-ssis-packages-from-tfs-vsts-build-release/

Let me know.

**Comment by linxtong** [comment]
Hi Mario,
Appreciate your kindly help.
I checked, we made a mistake, we searched Deploy SSIS after we installed it, so we cannot it add it into pipeline. **Actually we should search Deploy ISPACs.**

Thanks very much.
![Untitled](https://user-images.githubusercontent.com/3226285/54420025-e7de5780-4743-11e9-87b5-497cd0abd2b0.png)

**Comment by mmajcica** [comment]
No worries, a common mistake. I'll add ssis in the name of the task for the
next version.
