### ISSUE TITLE
Project & Environment Referencing issue

### ISSUE THREAD

**Issue by linxtong** [mmajcica/DeploySsis#14]
Hi Mario;

Hope you are doing well.
We deployed the projects with this task successfully at the first time. It works great, then we did some update, and deploy it again, we got below error. 
##[error]Exception calling "Add" with "2" argument(s): "An entry with the same key already exists."
An entry with the same key already exists.

I check the issues on this project, it is similar with the issue #6 .

So I did some testing work, I found when we checked the option of "Drop project before deploy", and deploy the project, then it works. 

I  thought it maybe the reference between environment and project was not deleted, when try to update the ssis project.

I test deployment with unchecked the option of "Drop project before deploy", and I deleted the reference in the SSIS DB with below sql.
`delete from [internal].[environment_references]`
The deployment finished successfully, but we want to keep the project versions, so we cannot checked the option after we deploy the code to production.

could you please have a look when you are free?

I was trying to do a pull request, but I failed on test the Powershell code on my local machine.
I checked code, I think the issue may be in below code, line 423 to line 432 of file ispac.psm1

```
if ($project.References[$EnvironmentName])
                    {
                        Write-Verbose "Project reference for the environment $EnvironmentName already exists"
                    }
                    else                        
                    {
                        Write-Verbose "Adding environment reference for $EnvironmentName to project $($project.Name)"
                        $project.References.Add($EnvironmentName, $FolderName)
                        $project.Alter() | Out-String | Write-Verbose
                    }
```

Thanks every much.

**Comment by mmajcica** [comment]
Hi,

the thing I'm doubting is that `$project.References[$EnvironmentName]` is problematic. There should be a a better way checking if the environment is already referenced. Check the following in understanding what could be the right way to leverage it https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.integrationservices.environmentreferencecollection?view=sqlserver-2017

I suspect that the above code (`$project.References[$EnvironmentName]`) returns always `false` and that the add reference is always called.

Unfortunately I have no SSIS instances around on which I could test this. So if you could do a quick test, it would be beneficial.

**Comment by linxtong** [comment]
Hi Mario,

Yes you are right.
I tested the code, I found   ($project.References[$EnvironmentName]) always returns false. because $project.References is object array, the code cannot work properly.

I test below code which works fine. could you please review it?
```

if ($project.References.Name -contains $EnvironmentName)
        {
            Write-Verbose "Project reference for the environment $EnvironmentName already exists"
        }
```
Could you please let me know after you release the fix?
Thanks a lot

**Comment by linxtong** [comment]
Hi Mario,

Thanks very much.
We tested the latest task in the Azure DevOps, it works great.

Best wishes.
