### ISSUE TITLE
Deploying SSIS Packages on-prem server from Azure Devops

### ISSUE THREAD

**Issue by ManikantaNani** [mmajcica/DeploySsis#15]
HI,
I am trying to deploy ssis package on my local machine. I have created a deployment group  and release pipeline. In release pipeline i have added deployment group added **Deploy ssis task** . I have filled all the details. when i run the release pipeline its throwing an error.
**Failed to connect server: localhost**

Please help me to solve this issue

**Comment by mmajcica** [comment]
It's all about your agent, where is the agent running?

**Comment by ManikantaNani** [comment]
Agent is running in my local machine.

**Comment by mmajcica** [comment]
Have you tried a simple powershell script locally to try to connect to
exclude configuration issues?

**Comment by ManikantaNani** [comment]
I have tried using powershell. I am able to connect to sql server and able to create SSISDB catalog and folder as well

**Comment by mmajcica** [comment]
What is the identity that your agent is running on?

**Comment by ManikantaNani** [comment]
with my windows credentials sql server Agent is running

**Comment by ManikantaNani** [comment]
Hi Mario,
Could you please help to solve this issue.Actually I am new to devops.
