### ISSUE TITLE
Project re-created in SSIS catalog

### ISSUE THREAD

**Issue by raducernea** [mmajcica/DeploySsis#2]
Hi Mario,

Thanks for creating the nice plugin. We try to use it to create a release pipeline in TFS and this is core component of the pipeline. 
Is it any way to avoid re-creating the project every time it is deployed?
Let me explain: we have two SSIS catalogs , in each we have one project and few different environments. 

The SSIS packages are called from some SQLServer Agent Jobs that pass the /ENVREFERENCE as parameter.  That is, as you know, the ID of the environment reference. Now the problem is that if the project is deleted, the envreference (linking the project to the environment) is of course also deleted.

I have to mention that we don't face this issue when deploying from Visual Studio (using project deployment mode)

Is it any way to fix this?

Many thanks,
Radu

**Comment by mmajcica** [comment]
Hi @raducernea,

I didn't know that for a single instance you can have multiple SSIS catalogs. I'm deploying multiple projects in different folders under the same catalog and in order to succeed in that, I'm using the 'Shared Catalog' option set to true.

> Shared Catalog: If not selected, prior the deployment of your packages, the catalog will be dropped. If marked as shared (e.g. in case it is used by other applications), the catalog will not be dropped and extra checks will be made during the deployment. In case you marked your catalog as shared but no catalog is present on the server, a new catalog will be created with a catalog password equal to 'P@ssw0rd'

Can you elaborate a bit more on your issue as I can't picture it at this moment.

**Comment by mmajcica** [comment]
I think that I do now get what you are saying.
Each time I do go to deploy a project I do drop it first.

Following is the code in the task responsible for that behaviour:
```
if($folder.Projects[$projectName])
{
	Write-Output "Dropping existing project $projectName"
	$folder.Projects[$projectName].Drop()
}

Write-Output "Deploying $projectName project..."

[byte[]]$ispac = [System.IO.File]::ReadAllBytes($ProjectFile.FullName)
$folder.DeployProject($projectName, $ispac) | Out-String | Write-Verbose
```
I'm not sure if this is a necessary step or it can be deployed even without dropping it. I'll check and if that turns not to be necessary, I'll addd another option where you will be able to influence this.

**Comment by raducernea** [comment]
That's exactly what I mean. Unfortunately I cannot do and test the code changes myself, since I am not the admin of our TFS installation (and I don't have a test environment installed locally). 
Thanks a lot Mario for looking into this!!

**Comment by mmajcica** [comment]
@raducernea I checked and it is possible to deploy a project without previously dropping in.
I implemented a new flag in the task called 'Drop project before deploy' which by default is set to true in order not to break the compatibility.
If I build you a new version of the extension, would you be able to test it?

**Comment by mmajcica** [comment]
You can find the VSIX package here https://github.com/mmajcica/DeploySsis/releases/download/1.0.4/mmajcica.deploy-ssis-1.0.4.vsix
