### ISSUE TITLE
Error deploying ispac after last update

### ISSUE THREAD

**Issue by RudyEvers** [mmajcica/DeploySsis#3]
Hi Mario,

Since today I'm having trouble deploying ispac files to my ssis catalog. Nothing changed in the release or build definitions. The error i'm receiving in the release log is:

##[error]Cannot process argument transformation on parameter 'ProjectFile'. Cannot convert value "False" to type "System.IO.FileInfo". Error: "Invalid cast from 'System.Boolean' to 'System.IO.FileInfo'."

I think it's got something to do with the new option "Drop project before deploy". When I turn the option on I get the error message: 

##[error]Cannot process argument transformation on parameter 'ProjectFile'. Cannot convert value "True" to type "System.IO.FileInfo". Error: "Invalid cast from 'System.Boolean' to 'System.IO.FileInfo'."

Hopefully you can help! 

Regards

**Comment by mmajcica** [comment]
Hi @RudyEvers ,

I'm sorry to hear that and it is my bad.
![image](https://user-images.githubusercontent.com/3026551/39287581-a4455866-4924-11e8-8e4a-907214e60c60.png)
I was too confident yesterday about a small change which obviously failed.
It should be fixed now in the version 1.0.5 that I just published.
Again, sorry for the inconvenience.
