### ISSUE TITLE
Support custom Windows username and password

### ISSUE THREAD

**Issue by simondel** [mmajcica/DeploySsis#4]
Right now this task supports either integrated auth using the current windows user or SQL auth. It would be nice to have an option to choose between using the current user for windows auth and using a custom username and password.

Would this be possible? It could also be a nice feature for the Deploy SSRS extension.

**Comment by mmajcica** [comment]
Dear Simon,

if I understand what you are suggesting is to have integrated authentication but not to run as the agent's identity (as currently is).
I am sure that there could be a chance to run the whole context of the script execution, but it will make the code cumbersome, not to speak about the fact that the account you have chosen for the execution would need to have sufficient rights on the build server.
All of this just pushes me to say it is something that I would not like to tackle. If you think that you could make it work, I'll be happy to accept a PR and discuss it.
The most common scenario is that your agent will run on a specific account of your choice, thus, integrated security will be fine as long as you grant specific permission to the account on which you are running your agent.
