### ISSUE TITLE
Link in title seems to be broken

### ISSUE THREAD

**Issue by steveculshaw** [mmajcica/DeploySsis#8]
The link in the title seems to be broken

Getting a 404 from ... http://blog.majcica.com/2018/02/26/deploy-ssis-packages-from-tfs-vsts-build-release/

But I can get to ... http://blog.majcica.com/2018/04/25/deploy-ssis-packages-from-tfs-vsts-build-release/

**Comment by mmajcica** [comment]
Corrected, thanks
